### ISSUE TITLE
Bot will come online for a short time and do nothing then disconnect

### ISSUE THREAD

**Issue by Rikimarueye** [sjkinnett1/cardian_discord#6]
As the title explains, this is the behavior. No error messages. Dragging the lua to luvit opens a window that populates and then closes.

**Comment by Rikimarueye** [comment]
I'm dumb. I fixed the issue. I am sowwi for wasting your time :<

**Comment by sjkinnett1** [comment]
Nice work, well done! :)  Hopefully it works well for you!  This is the first I've seen someone getting it working without my assistance but obviously not intentionally.  I hope it's working well for you!  I've started work on one that I hope is much simpler!
